version: "3.9"

services:
  # ---------------------------------------
  # 1. Load Balancer (Nginx)
  # ---------------------------------------
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro  <-- بدون فاصله
    depends_on:
      - flask-web
      - fast-web  # <--- وابستگی جدید

  # ---------------------------------------
  # 2. Flask Application (Legacy)
  # ---------------------------------------
  flask-web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 app:app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SELENIUM_HOST=selenium
      - DATABASE_URL=postgresql://postgres:123@db:5432/imdb_db
    depends_on:
      - redis
      - db
      - selenium
    deploy:
      replicas: 1  # یکی کافیست
    

  # ---------------------------------------
  # 3. FastAPI Application (New) - اضافه شده
  # ---------------------------------------
  fast-web:
    build: .  # از همان Dockerfile استفاده میکند (کدها مشترک)
    # اجرای Uvicorn روی پورت 8000
    command: uvicorn fast_app:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SELENIUM_HOST=selenium
      - DATABASE_URL=postgresql://postgres:123@db:5432/imdb_db
    depends_on:
      - redis
      - db
      - selenium
    deploy:
      replicas: 1
    restart: always

  # ---------------------------------------
  # 4. Celery Worker (Shared)
  # ---------------------------------------
  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SELENIUM_HOST=selenium
      - DATABASE_URL=postgresql://postgres:123@db:5432/imdb_db
    depends_on:
      - redis
      - selenium
      - db
    deploy:
      replicas: 2


  # ... (بقیه سرویس‌ها مثل selenium, redis, db بدون تغییر) ...
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: "2g"
    ports:
      - "4444:4444"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=imdb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
